### PR TITLE
Add smt-encoding "strategy"

### PR DESCRIPTION
**Pull request by shonfeder**
Towards meeting the short-term needs of https://github.com/informalsystems/apalache/issues/1099

The new strategy lets us get some immediate feedback on the performance of the array encoding vs. the oopsla encoding. The current ordering (10 using the oopsla encoding then 10 using the array encoding) is selected to show the trend in performance in the difference encodings as the length increases.

As per our discussion today, @rodrigo7491 will push any additional changes to this branch that he sees fit to meet the his near-term needs.

### CODE REVIEW

**Comment by shonfeder** [comment]
@rodrigo7491 here’s an example of the report generated with the current set up: https://github.com/informalsystems/apalache-tests/blob/46272492162fbef3ff80a401e71233ac99348424/results/010encoding-report.md

**Review by rodrigo7491 — COMMENTED** [review]
The changes LGTM and the example report is promising. I believe that there are two points we need to think about:

1) Can parametric instances be increased in size further? The example report shows that the new encoding starts to shine exactly on the largest instance, so I think it would be good to check even larger instances. Would the plots become unreadable if we simply add (tens of) new instances to `010encoding`?

2) Looking at the other parametric instances, I think the current arrays encoding should be able to also run on `SetAddDel`, `SetSndRcv`, and `SetSndRcv_NoFullDrop`. Should we make new strategies for each one, or is there a better way to run them?

**Comment by shonfeder** [comment]
- re: 1 -- How big would you like to go?
- re: 2 -- As a stop-gap hack, we can use the makefile to generate all the csv files based on a script that takes a feww  params. However, if you want to extend the functionality much beyond this, then let's just pivot to taking a fresh approach to the benchmarking. Sound OK?

**Comment by shonfeder** [comment]
- 1: I'll start with 30 for now. And we can see see how long that takes to run.
- 2: Let's stick with the hack for now, as a rework will be much more involved, and we'll want requirements and an issue to track it.

Since you think this looks ok in general, I'm gonna merge this in, then will add the additional extensions as followup. This should give us the ability to start running the strategy in isolation to improve the feedback loop.

**Comment by rodrigo7491** [comment]
What about the failing check? It didn't failed because of the run itself, but because of a failed push. Do you know what it is about?

**Review by rodrigo7491 — APPROVED** [review]
LGTM

**Comment by shonfeder** [comment]
Yeah, that's just because we already had a branch open with the name of the version (i.e., we had concurrent benchmarks running and there was a race condition over the branch name).

It might indicate we'll want to give branches of reports more specific names, but that's not particularly related to this change :)

**Pull request merged**
